/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package A06_swing.exemplos;

import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class MinhaJanelaBonita extends javax.swing.JFrame {

    /**
     * Creates new form MinhaJanelaBonita
     */
    public MinhaJanelaBonita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelValor1 = new javax.swing.JLabel();
        labelValor2 = new javax.swing.JLabel();
        labelResultado = new javax.swing.JLabel();
        textoValor1 = new javax.swing.JTextField();
        textoValor2 = new javax.swing.JTextField();
        botaoSomar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelValor1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelValor1.setText("Valor 1");

        labelValor2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelValor2.setText("Valor 2");

        labelResultado.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelResultado.setForeground(new java.awt.Color(255, 102, 102));
        labelResultado.setText("Resultado");

        textoValor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoValor1ActionPerformed(evt);
            }
        });

        textoValor2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        botaoSomar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botaoSomar.setText("+");
        botaoSomar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSomarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelValor2)
                                .addGap(18, 18, 18)
                                .addComponent(textoValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSomar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(labelResultado)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelValor1)
                            .addComponent(textoValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelValor2)
                            .addComponent(textoValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(botaoSomar)))
                .addGap(18, 18, 18)
                .addComponent(labelResultado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoValor1ActionPerformed

    private void botaoSomarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSomarMouseClicked
        try{
            String texto1 = textoValor1.getText();
            String texto2 = textoValor2.getText();
            double numero1 = Double.parseDouble(texto1);
            double numero2 = Double.parseDouble(texto2);
            double soma = numero1 + numero2;
            labelResultado.setText(""+soma);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao fazer a soma. Provável erro na entrada de dados.");
        }
    }//GEN-LAST:event_botaoSomarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinhaJanelaBonita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinhaJanelaBonita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinhaJanelaBonita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinhaJanelaBonita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinhaJanelaBonita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSomar;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JLabel labelValor1;
    private javax.swing.JLabel labelValor2;
    private javax.swing.JTextField textoValor1;
    private javax.swing.JTextField textoValor2;
    // End of variables declaration//GEN-END:variables
}
